-- =====================================================================
--  Orbit — database creation
--
--  Creates the orbit_database schema and its three tables on a fresh MySQL
--  instance. Run this first, then seed.sql if you want demo data.
--
--  Usage:
--      mysql -u root -p < db/schema.sql
--      mysql -u root -p orbit_database < db/seed.sql
--  or open each file in MySQL Workbench and run the whole script.
--
--  Requires MySQL 8.0 or newer (for the JSON column type and utf8mb4).
--
--  Safe to re-run. Everything is IF NOT EXISTS, so running it against a
--  database that already has data changes nothing.
--
--  ---------------------------------------------------------------------
--  Relationship to the Kotlin code
--  ---------------------------------------------------------------------
--  The source of truth for the schema is db/*Table.kt in the server. On
--  startup, DatabaseSchema.kt calls SchemaUtils.create(), which issues
--  CREATE TABLE IF NOT EXISTS for these same three tables. So strictly the
--  server can create them itself — this script exists so that:
--    * the database can be set up and inspected before the server runs,
--    * seed.sql can be loaded without starting the server first,
--    * the schema is readable in one place without reading Kotlin.
--
--  The DDL below mirrors what Exposed generates, INCLUDING the index names
--  (events_owner_id, ratings_event_id_user_id_unique, ...). That matters:
--  if the names differed, the server would see indexes it does not
--  recognise and could try to create its own copies alongside them.
--
--  If you change a *Table.kt file, change this file too. Neither Exposed's
--  SchemaUtils.create() nor this script ALTERs an existing table — see the
--  RESET section at the bottom.
--
--  ---------------------------------------------------------------------
--  Column conventions
--  ---------------------------------------------------------------------
--    * ids are VARCHAR(36) UUIDs generated by the Android client, so an
--      event keeps the same identity offline, on the server, and on a
--      phone it was shared to over P2P.
--    * start_time / created_at are BIGINT epoch MILLISECONDS, matching
--      System.currentTimeMillis() on the client.
--    * category / visibility store the Kotlin enum NAME ('SOCIAL',
--      'PUBLIC'), not its ordinal, so reordering the enum is safe.
--    * image_uris / interests are native JSON arrays.
--    * avg_rating / rating_count are denormalised from the ratings table
--      so listing events needs no join. The server recomputes them after
--      every rating change.
-- =====================================================================

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------
-- Database
--
-- utf8mb4, not utf8: MySQL's "utf8" is a legacy 3-byte encoding that
-- cannot store emoji. utf8mb4_unicode_ci rather than the MySQL 8 default
-- utf8mb4_0900_ai_ci so the script also runs on setups where the 0900
-- collations are unavailable; both sort Serbian text correctly.
-- ---------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS orbit_database
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE orbit_database;

-- ---------------------------------------------------------------------
-- users   (db/UserTable.kt)
--
-- No password column: there is no login. The id is the identifier the
-- client generates on first launch and sends in the X-User-Id header.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id           VARCHAR(36)  NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    interests    JSON         NOT NULL,

    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- events   (db/EventTable.kt)
--
-- The secondary indexes are on the columns the API filters by:
-- owner_id (my events), start_time (ordering), category and visibility
-- (search), access_code (joining a private event by code).
--
-- There is deliberately no synced_to_backend column. That flag answers
-- "has the server seen this yet?", which only the client needs to ask.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
    id                   VARCHAR(36)  NOT NULL,
    owner_id             VARCHAR(36)  NOT NULL,
    title                VARCHAR(200) NOT NULL,
    description          TEXT         NOT NULL,

    latitude             DOUBLE       NOT NULL,
    longitude            DOUBLE       NOT NULL,
    address              VARCHAR(300)     NULL,

    start_time           BIGINT       NOT NULL,
    duration_minutes     INT              NULL,

    category             VARCHAR(32)  NOT NULL,
    visibility           VARCHAR(16)  NOT NULL,

    image_uris           JSON         NOT NULL,

    capacity             INT              NULL,
    price                DOUBLE           NULL,
    requires_reservation TINYINT(1)   NOT NULL DEFAULT 0,

    access_code          VARCHAR(8)       NULL,

    avg_rating           FLOAT        NOT NULL DEFAULT 0,
    rating_count         INT          NOT NULL DEFAULT 0,

    created_at           BIGINT       NOT NULL,

    PRIMARY KEY (id),
    KEY events_owner_id    (owner_id),
    KEY events_start_time  (start_time),
    KEY events_category    (category),
    KEY events_visibility  (visibility),
    KEY events_access_code (access_code)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- ratings   (db/RatingTable.kt)
--
-- The unique key on (event_id, user_id) enforces one rating per person
-- per event in the database itself, so two simultaneous requests cannot
-- both insert. Re-rating updates the existing row.
--
-- No FOREIGN KEY to events, matching the Kotlin table definition. Deleting
-- an event therefore leaves its ratings behind; the API refuses to rate an
-- event that does not exist, so new orphans cannot be created through it.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ratings (
    id         VARCHAR(36) NOT NULL,
    event_id   VARCHAR(36) NOT NULL,
    user_id    VARCHAR(36) NOT NULL,
    value      INT         NOT NULL,
    comment    TEXT            NULL,
    created_at BIGINT      NOT NULL,

    PRIMARY KEY (id),
    UNIQUE KEY ratings_event_id_user_id_unique (event_id, user_id),
    KEY ratings_event_id (event_id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- Optional: a dedicated application user
--
-- The server defaults to root with no password (application.yaml). On
-- most machines root has a password, and running an app as root means a
-- bug can touch every schema on the instance. To use a dedicated account
-- instead, uncomment this block, pick a password, and start the server
-- with the matching environment variables:
--
--     DB_USER=orbit  DB_PASSWORD=<your password>  ./gradlew run
--
-- Never commit the real password to this file.
-- ---------------------------------------------------------------------
-- CREATE USER IF NOT EXISTS 'orbit'@'localhost' IDENTIFIED BY 'change-me';
-- GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX
--     ON orbit_database.* TO 'orbit'@'localhost';
-- FLUSH PRIVILEGES;

-- ---------------------------------------------------------------------
-- RESET (destructive — commented out on purpose)
--
-- Neither this script nor the server alters an existing table. After
-- changing a column in a *Table.kt file, drop the tables and run this
-- script again. This deletes ALL data, not just the seed rows.
-- ---------------------------------------------------------------------
-- DROP TABLE IF EXISTS ratings;
-- DROP TABLE IF EXISTS events;
-- DROP TABLE IF EXISTS users;

-- ---------------------------------------------------------------------
-- Summary
-- ---------------------------------------------------------------------
SELECT table_name AS created_table
FROM information_schema.tables
WHERE table_schema = 'orbit_database'
ORDER BY table_name;
