# JVM argumenti za Gradle daemon (memorija)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# Paralelni build, samo za razdvojene projekte
# org.gradle.parallel=true
# Koristi AndroidX pakete
android.useAndroidX=true
# Kotlin stil koda: official ili obsolete
kotlin.code.style=official
# Svaka biblioteka dobija svoju, manju R klasu
android.nonTransitiveRClass=true