ktor:
  deployment:
    port: 8080
  application:
    # Puna imena klasa: Foo.kt postaje FooKt
    modules:
      - com.example.orbit.plugins.SerializationKt.configureSerialization
      - com.example.orbit.plugins.StatusPagesKt.configureStatusPages
      - com.example.orbit.plugins.SecurityKt.configureSecurity
      - com.example.orbit.plugins.DatabasesKt.configureDatabases
      - com.example.orbit.plugins.RoutingKt.configureRouting

storage:
  url: "$DB_URL:r2dbc:mysql://localhost:3306/orbit_database"
  user: "$DB_USER:root"
  password: "$DB_PASSWORD:"
